### ISSUE TITLE
Single Module doesn't work

### ISSUE THREAD

**Issue by stephengolub** [smaye81/karma-ng-json2js-preprocessor-requirejs#1]
I'm getting a "Missing ; before statement" on line 10 of each of my files if I set "moduleName".

**Comment by smaye81** [comment]
Can you send me the karma config file you're using?

On Thu, Jul 10, 2014 at 10:39 AM, Stephen Golub notifications@github.com
wrote:

> I'm getting a "Missing ; before statement" on line 10 of each of my files
> if I set "moduleName".
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/smaye81/karma-ng-json2js-preprocessor-requirejs/issues/1
> .

## 

Steve Ayers

Senior Technical Consultant | Summa
[m]  412.708.2828
steve.ayers@summa-tech.com dfm@summa-tech.com

http://www.summa-tech.com

**Comment by stephengolub** [comment]
Sorry for the long delay in getting back to you.

I've since lost the configuration that I had, but let me see if I can remember it:

``` javascript
/* jshint node:true */
module.exports = function(config) {
    config.set({
        // base path, that will be used to resolve files and exclude
        basePath: 'app/',


        // frameworks to use
        frameworks: ['mocha', 'chai', 'sinon-chai'],
        hostname: '127.0.0.1',

        // list of files / patterns to load in the browser
        files: [
            'bower_components/jquery/jquery.min.js',
            'bower_components/angular/angular.js',
            'bower_components/angular-animate/angular-animate.js',
            'bower_components/angular-cookies/angular-cookies.js',
            'bower_components/angular-mocks/angular-mocks.js',
            'bower_components/angular-resource/angular-resource.js',
            'bower_components/angular-hotkeys/build/hotkeys.min.js',
            'bower_components/angular-route/angular-route.js',
            'bower_components/angular-sanitize/angular-sanitize.js',
            'bower_components/newrelic-timing/newrelic-timing.js',
            'bower_components/newrelic-timing/newrelic-timing-angular.js',
            'bower_components/angular-xeditable/dist/js/xeditable.js',
            'bower_components/angular-rx-data-table/dist/scripts/rx-data-table.js',
            'bower_components/lodash/dist/lodash.js',
            'bower_components/mousetrap/mousetrap.js',
            'bower_components/momentjs/moment.js',
            'lib/*.js',
            'scripts/**/*.js',
            '../test/browser-helpers.js',
            '../test/api-mocks/responses/**/*.json',
            'views/**/*.html' // templates
        ],

        // list of files to exclude
        exclude: [],

        preprocessors: {
            'views/**/*.html': 'ng-html2js',
            'modules/**/*.html': 'ng-html2js',
            '../test/api-mocks/responses/**/*.json': ['json2js'],
            'scripts/**/!(*.spec).js': ['coverage']
        },

        // test results reporter to use
        reporters: ['mocha', 'coverage'],
        // reporters: ['mocha', 'coverage', 'threshold'],

        thresholdReporter: {
            statements: 90,
            branches: 60,
            functions: 85,
            lines: 90
        },

        ngJson2JsPreprocessor: {
            moduleName : "stubs",
            stripPrefix: '../test/api-mocks/responses/**/*.json',
            prependPrefix: 'served/',
        },

        coverageReporter: {
            type: 'html',
            dir: '../coverage/'
        },

        // web server port
        port: 9876,


        // enable / disable colors in the output (reporters and logs)
        colors: true,


        // level of logging
        // possible values:
        //  config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
        logLevel: config.LOG_INFO,


        // enable / disable watching file and executing tests whenever any file changes
        autoWatch: true,


        // Start these browsers, currently available:
        // - Chrome
        // - ChromeCanary
        // - Firefox
        // - Opera
        // - Safari (only Mac)
        // - PhantomJS
        // - IE (only Windows)
        browsers: ['PhantomJS'],

        // If browser does not capture in given timeout [ms], kill it
        captureTimeout: 60000,


        // Continuous Integration mode
        // if true, it capture browsers, run tests and exit
        singleRun: false
    });
};
```

**Comment by smaye81** [comment]
So, two things.  One is a bug that I actually just found yesterday and one
I noticed in your config file.

First, make sure you have 'enableRequireJs : true' in your
ngJson2JsPreprocessor block.  That is a bug.  This should be true by
default, but if you leave it out, the require define wrapper is never put
in.  I will fix that hopefully today.

Second, not sure if this was a typo or not, but in your preprocessor block,
you should have this (you were missing the 'ng-')

'../test/api-mocks/responses/*_/_.json': ['ng-json2js'],

If neither of these help, send me one of your JSON files.  We'll get
it figured out.

On Wed, Jul 23, 2014 at 9:47 AM, Stephen Golub notifications@github.com
wrote:

> Sorry for the long delay in getting back to you.
> 
> I've since lost the configuration that I had, but let me see if I can
> remember it:
> 
> /\* jshint node:true */module.exports = function(config) {
>     config.set({
>         // base path, that will be used to resolve files and exclude
>         basePath: 'app/',
> 
> ```
>     // frameworks to use
>     frameworks: ['mocha', 'chai', 'sinon-chai'],
>     hostname: '127.0.0.1',
> 
>     // list of files / patterns to load in the browser
>     files: [
>         'bower_components/jquery/jquery.min.js',
>         'bower_components/angular/angular.js',
>         'bower_components/angular-animate/angular-animate.js',
>         'bower_components/angular-cookies/angular-cookies.js',
>         'bower_components/angular-mocks/angular-mocks.js',
>         'bower_components/angular-resource/angular-resource.js',
>         'bower_components/angular-hotkeys/build/hotkeys.min.js',
>         'bower_components/angular-route/angular-route.js',
>         'bower_components/angular-sanitize/angular-sanitize.js',
>         'bower_components/newrelic-timing/newrelic-timing.js',
>         'bower_components/newrelic-timing/newrelic-timing-angular.js',
>         'bower_components/angular-xeditable/dist/js/xeditable.js',
>         'bower_components/angular-rx-data-table/dist/scripts/rx-data-table.js',
>         'bower_components/lodash/dist/lodash.js',
>         'bower_components/mousetrap/mousetrap.js',
>         'bower_components/momentjs/moment.js',
>         'lib/*.js',
>         'scripts/**/*.js',
>         '../test/browser-helpers.js',
>         '../test/api-mocks/responses/**/*.json',
>         'views/**/*.html' // templates
>     ],
> 
>     // list of files to exclude
>     exclude: [],
> 
>     preprocessors: {
>         'views/**/*.html': 'ng-html2js',
>         'modules/**/*.html': 'ng-html2js',
>         '../test/api-mocks/responses/**/*.json': ['json2js'],
>         'scripts/**/!(*.spec).js': ['coverage']
>     },
> 
>     // test results reporter to use
>     reporters: ['mocha', 'coverage'],
>     // reporters: ['mocha', 'coverage', 'threshold'],
> 
>     thresholdReporter: {
>         statements: 90,
>         branches: 60,
>         functions: 85,
>         lines: 90
>     },
> 
>     ngJson2JsPreprocessor: {
>         moduleName : "stubs",
>         stripPrefix: '../test/api-mocks/responses/**/*.json',
>         prependPrefix: 'served/',
>     },
> 
>     coverageReporter: {
>         type: 'html',
>         dir: '../coverage/'
>     },
> 
>     // web server port
>     port: 9876,
> 
> 
>     // enable / disable colors in the output (reporters and logs)
>     colors: true,
> 
> 
>     // level of logging
>     // possible values:
>     //  config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
>     logLevel: config.LOG_INFO,
> 
> 
>     // enable / disable watching file and executing tests whenever any file changes
>     autoWatch: true,
> 
> 
>     // Start these browsers, currently available:
>     // - Chrome
>     // - ChromeCanary
>     // - Firefox
>     // - Opera
>     // - Safari (only Mac)
>     // - PhantomJS
>     // - IE (only Windows)
>     browsers: ['PhantomJS'],
> 
>     // If browser does not capture in given timeout [ms], kill it
>     captureTimeout: 60000,
> 
> 
>     // Continuous Integration mode
>     // if true, it capture browsers, run tests and exit
>     singleRun: false
> });};
> ```
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/smaye81/karma-ng-json2js-preprocessor-requirejs/issues/1#issuecomment-49875357
> .

## 

Steve Ayers

Senior Technical Consultant | Summa
[m]  412.708.2828
steve.ayers@summa-tech.com dfm@summa-tech.com

http://www.summa-tech.com

**Comment by stephengolub** [comment]
Yea, the missing ng- is a typo.

_Stephen Golub_

**Comment by smaye81** [comment]
Did the enableRequireJs workaround do the trick?  Just as an FYI, I pushed up a fix for this, so enableRequireJs should always default to true.
